
site_name: ChatGPT Discord Bot
site_description: Documentation for setup, configuration, and usage
site_url: https://doubleangels.github.com/chatgpt

repo_url: https://github.com/doubleangels/chatgpt
repo_name: doubleangels/chatgpt

docs_dir: docs
use_directory_urls: true

theme:
  name: null
  custom_dir: mkdocs-material/material

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Configuration: configuration.md
  - Docker Deployment: docker.md
  - Commands: commands.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables

