# GitHub Pages configuration for this repo's documentation site

title: ChatGPT Discord Bot
description: Documentation for setup, configuration, and usage
theme: jekyll-theme-cayman

# Site URL and base path for GitHub Pages
url: "https://doubleangels.github.com"
baseurl: "/chatgpt"

markdown: kramdown
exclude:
  - node_modules
  - vendor

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

github:
  is_project_page: true

